### PR TITLE
change private to protected

### PR DESCRIPTION
**Pull request by zacksleo**
For the reason easy to expand. When users what to do some extension, they can easy to deal with the file object.

eg.  I what to store the file into into the database after upload.

### CODE REVIEW

**Comment by mohorev** [comment]
@zacksleo Check PR please. This fix solves your problem?

**Comment by zacksleo** [comment]
@mohorev  thanks, #40 is better, I will update my code.

**Comment by zacksleo** [comment]
Resolved.

**Comment by mohorev** [comment]
@zacksleo Merged. See tag https://github.com/mohorev/yii2-upload-behavior/releases/tag/0.1.7

**Pull request closed without merging**
